<a href="https://colab.research.google.com/github/honggilgim/python_test_with_colab/blob/main/%ED%86%B5%EA%B3%84%EB%9F%89_%EC%8B%A4%EC%8A%B5_%EB%B0%8F_%EC%B9%B4%EC%9D%B4%EC%A0%9C%EA%B3%B1%2C_t%2C_%EC%8C%8D%EC%B2%B4_%EA%B2%80%EC%A6%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# 통계량 실습. numpy 를 활용하여 통계량 계산

import numpy as np

x = np.arange(10.0) # 0~9 까지의 실수 10개를 가지는 자료 구조 생성
x.mean() # 평균 구하는 함수

4.5

In [4]:
numbers = np.arange(20.0) # 0~19 까지 실수 20개로 1차원 배열 생성
x = np.reshape(numbers,(4,5)) # numbers를 4행 5열로 변경
np.mean(x,0)

array([ 7.5,  8.5,  9.5, 10.5, 11.5])

In [5]:
np.std(x) # 행과 열을 고려하지 않고 x에 대한 표준편차 구하기

5.766281297335398

In [6]:
np.var(x) # 마찬가지로, 행과 열을 고려하지 않고 분산 구하기

33.25

In [7]:
x = np.random.randn(3,4) # 3행 4열인 x
# x 행별로 피어슨 상관관계 구하기, 예를 들어 1행과 2행의 상관관계 2행과 3행의 상관관계 등.
# 결과는 3 3 행렬로 나오며 랜덤하게 형성되어 결과가 달라질 수가 있음.

In [8]:
np.corrcoef(x)

array([[ 1.        , -0.21923607, -0.8815205 ],
       [-0.21923607,  1.        , -0.10073848],
       [-0.8815205 , -0.10073848,  1.        ]])

In [9]:
np.corrcoef(x[0],x[1])

array([[ 1.        , -0.21923607],
       [-0.21923607,  1.        ]])

In [10]:
# x의 각 열 사이의 공분산 구하기, 총 4행 4열의 결과값이 출력되어 랜덤하게 생성
np.cov(x, rowvar=False)

array([[ 0.63157178, -0.24476256,  0.5315622 , -0.88336616],
       [-0.24476256,  0.48960083, -0.35284441,  0.06092677],
       [ 0.5315622 , -0.35284441,  0.50201189, -0.63880099],
       [-0.88336616,  0.06092677, -0.63880099,  1.43617123]])

In [11]:
#x의 각 행 사이의 공분산 구하기, 총 3행 3열의 결괏값이 출력되며 랜덤하게 생성되어 결과는 다를 수 있음.
np.cov(x, rowvar=True)

array([[ 1.32543484, -0.17325673, -0.64301902],
       [-0.17325673,  0.47119193, -0.04381336],
       [-0.64301902, -0.04381336,  0.4014435 ]])

In [12]:
# 다양한 확률 분포 사용하기

import numpy as np
from scipy import stats
np.random.seed(0)
stats.binom(10,0.5).rvs(10)
# n=10, p=0.5인 이항 분포에서 rvs함수로 표본을 10개 추출

array([5, 6, 5, 5, 5, 6, 5, 7, 8, 5])

In [13]:
stats.norm.rvs(0)
# 평균은 0이고, 표준편차가 1인 정규 분포에서 표본 10개 추출

0.144043571160878

In [14]:
stats.uniform.rvs(10)
# 0~1 사이에 정의된 균일 분포에서 표본 10개 추출

10.568044561093933

In [15]:
stats.chi2(df=2).rvs(10)
# 자유도가 2인 카이제곱 분포에서 표본 10개 추출

array([5.19650831, 0.14737071, 0.18232206, 0.04085117, 3.57497536,
       3.01156846, 4.08062856, 7.69044368, 3.21047912, 1.23785892])

In [18]:
# 카이제곱 검정

import scipy as sp
n = np.array([1,2,4,1,2,10])
# 주사위를 20번 던졌을 때, 1~6 사이의 눈이 나오는 빈도

sp.stats.chisquare(n)
# 귀무 가설 : 각 눈의 빈도는 동일한 확률로 나온다.
# 결과에 대한 고찰 : 귀무 가설 기각

Power_divergenceResult(statistic=17.799999999999997, pvalue=0.0032077920346052823)

In [19]:
# t 검증하기

np.random.seed(0)
x1 = stats.norm(0,1 ).rvs(10) # 평균이 0인 정규 분포에서 표본 10개 추출
x2 = stats.norm(1,1).rvs(10) # 평균이 1인 정규 분포에서 표본 10개 추출
np.mean(x1), np.mean(x2)
stats.ttest_ind(x1,x2) # 두 집단의 모평균이 같다는 귀무 가설에 대해 t- 검정
# 결과에 대한 고찰 : 결과는 10%로 유의 수준에서 귀무 가설을 기각한다.

Ttest_indResult(statistic=-1.6868710732328158, pvalue=0.10888146383913824)

In [22]:
# 쌍체 t 검정하기

# 어떤 처치의 전후로 통증 크기를 before와 after로 기록하였다. 처치 전의 평균과 처치 후의 평균이 차이가 있는지 쌍체 검정 t로 확인하기
# 숫자가 클수록 통증이 심하며, 통증은 0~100 사이의 값으로 표현한다.

before = [68,56,57,54,64,48,68,56,61,58,67,49,58,58,65,54,59,55,60,62]
after = [65,57,57,54,64,47,67,54,60,58,65,48,57,56,64,53,57,55,61,63]


# 귀무 가설은 처치 전후로 통증의 차이가 없고, 대립 가설은 통증의 차이가 있음

In [23]:
stats.ttest_rel(before, after)
# 유의 수준이 5% 라면 현재 p 값이 유의 수준보다 작으므로 귀무 가설을 기각한다.

Ttest_relResult(statistic=3.0, pvalue=0.007361724183868639)

In [24]:
# 고객 5명에게 광고 전후로 제품에 대한 선호도를 측정하였을 때,
# 광고 효과가 있는지 확인하기, 1~10 사이의 값으로 측정하며 10은 제품을 매우 선호하고, 1은 제품을 선호하지 않는다.

before = [2,3,2,3,2]
after = [9,8,9,7,6]

# 귀무 가설로는 광고 전후로 선호도 차이가 없고, 대립 가설로는 선호도 차이가 있음.

In [25]:
stats.ttest_rel(before, after)
# 유의 수준이 5% 라면 현재 p값이 유의 수준보다 작으므로 귀무 가설을 기각.

Ttest_relResult(statistic=-7.961865632364446, pvalue=0.001348170975769803)