In [1]:
import numpy as np

In [2]:
arr = np.array([[2,3],[1,2]])

In [4]:
np.dot(arr,arr)

array([[ 7, 12],
       [ 4,  7]])

In [5]:
np.inner(arr,arr)

array([[13,  8],
       [ 8,  5]])

In [13]:
ar2 = np.array([[3,6,9],[6,9,3],[3,9,6]])

In [14]:
np.unique(ar2)

array([3, 6, 9])

In [16]:
arr1 = np.array([3,6,9])

In [10]:
arr2 = np.array([6,9,3])

In [11]:
arr3 = np.array([3,9,6])

In [17]:
np.unique(arr1)

array([3, 6, 9])

In [18]:
import numpy.linalg as alg

A=np.array([[3,6,9],[6,9,3],[3,9,6]])
_eigenvalue,_eigenvector=alg.eig(A)
print(_eigenvalue)
print(_eigenvector)

[ 1.80000000e+01+0.j -6.10622664e-16+3.j -6.10622664e-16-3.j]
[[ 0.57735027+0.j          0.74678799+0.j          0.74678799-0.j        ]
 [ 0.57735027+0.j         -0.41202096-0.28326441j -0.41202096+0.28326441j]
 [ 0.57735027+0.j          0.02575131+0.43777227j  0.02575131-0.43777227j]]


In [19]:
np.linalg.eig(ar2)

(array([ 1.80000000e+01+0.j, -6.10622664e-16+3.j, -6.10622664e-16-3.j]),
 array([[ 0.57735027+0.j        ,  0.74678799+0.j        ,
          0.74678799-0.j        ],
        [ 0.57735027+0.j        , -0.41202096-0.28326441j,
         -0.41202096+0.28326441j],
        [ 0.57735027+0.j        ,  0.02575131+0.43777227j,
          0.02575131-0.43777227j]]))