<a href="https://colab.research.google.com/github/honggilgim/python_test_with_colab/blob/main/3_3array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([[2,3],[1,2]])

In [ ]:
np.dot(arr,arr)

array([[ 7, 12],
       [ 4,  7]])

In [ ]:
np.inner(arr,arr)

array([[13,  8],
       [ 8,  5]])

In [ ]:
ar2 = np.array([[3,6,9],[6,9,3],[3,9,6]])

In [ ]:
np.unique(ar2)

array([3, 6, 9])

In [ ]:
arr1 = np.array([3,6,9])

In [ ]:
arr2 = np.array([6,9,3])

In [ ]:
arr3 = np.array([3,9,6])

In [ ]:
np.unique(arr1)

array([3, 6, 9])

In [ ]:
import numpy.linalg as alg

A=np.array([[3,6,9],[6,9,3],[3,9,6]])
_eigenvalue,_eigenvector=alg.eig(A)
print(_eigenvalue)
print(_eigenvector)

[ 1.80000000e+01+0.j -6.10622664e-16+3.j -6.10622664e-16-3.j]
[[ 0.57735027+0.j          0.74678799+0.j          0.74678799-0.j        ]
 [ 0.57735027+0.j         -0.41202096-0.28326441j -0.41202096+0.28326441j]
 [ 0.57735027+0.j          0.02575131+0.43777227j  0.02575131-0.43777227j]]


In [ ]:
np.linalg.eig(ar2)

(array([ 1.80000000e+01+0.j, -6.10622664e-16+3.j, -6.10622664e-16-3.j]),
 array([[ 0.57735027+0.j        ,  0.74678799+0.j        ,
          0.74678799-0.j        ],
        [ 0.57735027+0.j        , -0.41202096-0.28326441j,
         -0.41202096+0.28326441j],
        [ 0.57735027+0.j        ,  0.02575131+0.43777227j,
          0.02575131-0.43777227j]]))